from pathlib import Path
p=Path('frontend/src/App.tsx');s=p.read_text(encoding='utf-8-sig');s=s[:s.index('function StaffPortal(')]
s=s.replace('  type Portal,\n','').replace('  type Submission,\n','')
s=s.replace('import { Schedule } from "./Schedule";','import { Schedule } from "./Schedule";\nimport { Employee } from "./Employee";\nimport { ManagerAccess } from "./ManagerAccess";\nimport { DemandProposal } from "./DemandProposal";\nimport { TimeUnit } from "./ui";')
s=s.replace('return token ? <StaffPortal token={token} /> : <Manager />;','return token ? <Employee token={token} /> : <ManagerAccess><Manager /></ManagerAccess>;')
s=s.replace('state.candidates.filter((c) => c.period === period?.id)','state.candidates.filter((c) => c.period === period?.id && !c.archived)')
s=s.replace('<div className={`app ${collapsed ? "collapsed" : ""}`}>','<TimeUnit.Provider value={state.store.step}><div className={`app ${collapsed ? "collapsed" : ""}`}>')
s=s.replace('      {modal}\n    </div>','      {modal}\n    </div></TimeUnit.Provider>')
s=s.replace('<span className="manager-avatar">店</span>','<button className="text-button" onClick={async()=>{await api("/auth/logout","POST");location.reload()}}>ログアウト</button>')
s=s.replace('カレンダー表示単位','勤務時間の入力単位').replace('as 30 | 60','as 15 | 30 | 60').replace('<option value={30}>30分</option>','<option value={15}>15分</option><option value={30}>30分（標準）</option>').replace('<option value={60}>60分</option>','<option value={60}>1時間</option>')
s=s.replace('割当・検証は30分単位です。日をまたぐ営業時間には対応していません。','従業員の入力・自動作成・手動編集に同じ単位を使います。単位変更で合わなくなる既存の時刻は、丸めずに警告します。')
s=s.replace('label="基本営業開始"','label="基本営業開始" step={store.step}').replace('label="基本営業終了"','label="基本営業終了" step={store.step}')
s=s.replace('アカウント登録不要。データはこのPCに保存されます。','データはこのPCに保存されます。')
s=s.replace('希望を集めて、無理のないシフトを。今期の状況を確認しましょう。','希望の提出状況と、確定までの作業を確認できます。')
s=s.replace('30分単位で集計','設定した勤務時間単位で集計')
s=s.replace('<h2>曜日テンプレート・特定日の上書き</h2>','<h2>曜日テンプレート・特定日の上書き</h2><button disabled={locked} onClick={()=>M(<DemandProposal state={state} period={period} close={()=>M(null)} save={accept}/>)}>実績から提案</button>')
s=s.replace('key={period.id + ":" + candidates.length}','key={period.id + ":" + (candidates[0]?.id||"empty")}')
# GET enriches cost metrics but specialized mutation endpoints are intentionally unchanged.
s=s.replace('state.roles.map((r) => (','state.roles.map((r) => (')
p.write_text(s,encoding='utf-8')
p=Path('frontend/src/Schedule.tsx');s=p.read_text(encoding='utf-8-sig').replace('state.candidates.filter((c) => c.period === period.id)','state.candidates.filter((c) => c.period === period.id && !c.archived)')
s=s.replace('import { Modal, Field, Time, Empty } from "./ui";','import { Modal, Field, Time, Empty } from "./ui";\nimport { LaborChart } from "./LaborChart";\nimport { DayTimeline } from "./DayTimeline";')
s=s.replace('<Tabs.Root defaultValue="calendar">','<Tabs.Root defaultValue="timeline">').replace('<Tabs.List className="tabs no-print" aria-label="シフト表示">','<Tabs.List className="tabs no-print" aria-label="シフト表示"><Tabs.Trigger value="timeline">1日の配置</Tabs.Trigger>')
s=s.replace('<Tabs.Content value="calendar">','<Tabs.Content value="timeline"><DayTimeline state={state} period={period} candidate={c} onEdit={E}/></Tabs.Content><Tabs.Content value="calendar">')
s=s.replace('<h3>スタッフごとの勤務時間</h3>','<LaborChart state={state} candidate={c}/><h3>スタッフごとの勤務時間</h3>')
s=s.replace('slotDuration={hm(state.store!.step)}','slotDuration={hm(state.store!.step)} snapDuration={hm(state.store!.step)}')
s=s.replace('state.roles.map((r) => (','state.roles.filter(r=>state.staff.find(s=>s.id===edit.staff)?.roles.includes(r.id)).map((r) => (')
s=s.replace('a.role === "lead"\n                          ? "#25485d"\n                          : a.role === "kitchen"\n                            ? "#46786f"\n                            : "#628898"','["#406b5c","#576c8c","#916f4b","#707846"][state.roles.findIndex(r=>r.id===a.role)%4]')
p.write_text(s,encoding='utf-8')
