import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";

test("運営者が加盟店の3画面を作り、請求と入金を管理する", async ({ page, browser }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/platform");
  await page.getByLabel("運営者パスワード").fill("operator-password-123");
  await page.getByLabel("パスワードをもう一度").fill("operator-password-123");
  await page.getByRole("button", { name: "運営者アカウントを作成" }).click();
  await expect(page.getByRole("heading", { name: "概要" })).toBeVisible();
  await page.getByRole("button", { name: "加盟店", exact: true }).click();
  await page.getByRole("button", { name: "加盟店を登録" }).click();
  await page.getByLabel("加盟店ID（URLに使用）").fill("alpha-shop");
  await page.getByLabel("表示名").fill("アルファ店");
  await page.getByLabel("契約名義").fill("アルファ株式会社");
  await page.getByLabel("月額料金（税抜・円）").fill("10000");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await page.getByRole("button", { name: /アルファ店.*alpha-shop/ }).click();
  await page.getByRole("button", { name: "専用環境を作成" }).click();
  await expect(page.getByRole("heading", { name: "管理者の初回設定キー" })).toBeVisible();
  await expect(page.getByRole("link", { name: "従業員画面 ↗" })).toHaveAttribute("href", /\/s\/alpha-shop\/employee$/);
  const setupKey = (await page.locator(".platform-setup-key code").textContent())!.trim();
  await page.getByRole("button", { name: "表示を閉じる" }).click();
  const context = await browser.newContext();
  const manager = await context.newPage();
  await manager.goto("/s/alpha-shop/admin");
  await expect(manager.getByRole("heading", { name: "管理者のメールを確認" })).toBeVisible();
  await manager.getByLabel("管理者メールアドレス").fill("manager@alpha.example.com");
  await manager.getByLabel("初回設定キー").fill(setupKey);
  await manager.getByRole("button", { name: "設定リンクを送る" }).click();
  await expect(manager.getByText("パスワード設定リンクをメールで送りました。30分以内に開いてください。")).toBeVisible();
  const mail = JSON.parse(await readFile("test-results/manager-mailbox.json", "utf-8"));
  expect(mail.email).toBe("manager@alpha.example.com");
  const managerSetup = await context.newPage();
  await managerSetup.goto(mail.link);
  await expect(managerSetup.getByRole("heading", { name: "管理者パスワードを設定" })).toBeVisible();
  await managerSetup.getByLabel("管理者パスワード", { exact: true }).fill("merchant-password-123");
  await managerSetup.getByLabel("パスワードをもう一度").fill("merchant-password-123");
  await managerSetup.getByRole("button", { name: "パスワードを設定" }).click();
  await expect(managerSetup.getByRole("heading", { name: "店舗のシフト管理を始める" })).toBeVisible();
  await managerSetup.request.post("/s/alpha-shop/api/auth/logout");
  await managerSetup.goto("/s/alpha-shop/admin");
  await managerSetup.getByLabel("管理者メールアドレス").fill("manager@alpha.example.com");
  await managerSetup.getByLabel("管理者パスワード", { exact: true }).fill("merchant-password-123");
  await managerSetup.getByRole("button", { name: "ログイン" }).click();
  await expect(managerSetup.getByRole("heading", { name: "店舗のシフト管理を始める" })).toBeVisible();
  expect((await manager.request.get("/api/platform/merchants")).status()).toBe(401);
  await context.close();
  await page.getByRole("button", { name: "契約・連絡先を編集" }).click();
  await page.getByLabel("利用状態").selectOption("利用中");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await page.getByRole("button", { name: "請求元設定" }).click();
  await page.getByLabel("請求元の名称").fill("シフトノート運営");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await page.getByRole("button", { name: "請求・入金" }).click();
  await page.getByLabel("加盟店", { exact: true }).selectOption({ label: "アルファ店" });
  await page.getByRole("button", { name: "下書きを作成" }).click();
  await expect(page.getByRole("cell", { name: /11,000/ }).first()).toBeVisible();
  await page.getByRole("button", { name: "確認" }).click();
  await page.getByRole("button", { name: "内容を確認して発行" }).click();
  await expect(page.getByRole("heading", { name: /請求書 SN-/ })).toBeVisible();
  await page.getByRole("button", { name: "記録", exact: true }).click();
  await expect(page.getByRole("cell", { name: "入金済み" })).toBeVisible();
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: "../artifacts/platform-mobile.png", fullPage: true });
  expect(errors).toEqual([]);
});
